# Generated by Django 5.1.5 on 2025-02-11 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_add_task_statuses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
